### ISSUE TITLE
Syntax Errors in Wild Shape Macro

### ISSUE THREAD

**Issue by Sebmaster777** [websterguy/pf1-mighty-morphin-mod#11]
Tried to use wild shape macro on a level 20 druid, but seems to not be working

**Comment by websterguy** [comment]
Was this a version of the macro you've had in your world for a while or a 
new copy from the compendium? I updated the wild shape macro a few versions 
back.

From: Sebmaster777 ***@***.***) To: 
***@***.***: 
***@***.***: 5/18/2022 1:58:53 
AMSubject: [websterguy/pf1-mighty-morphin-mod] Syntax Errors in Wild 
Shape Macro (Issue #11)

Tried to use wild shape macro on a level 20 druid, but seems to not be 
working
—Reply 
to this email directly, view it on 
GitHub, or unsubscribe.You 
are receiving this because you are subscribed to this thread.Message 
ID: 
***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/websterguy/pf1-mighty-morphin-mod/issues/11",
"url": "https://github.com/websterguy/pf1-mighty-morphin-mod/issues/11",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Sebmaster777** [comment]
I just grabbed it from the compendium after the update
